export interface CountryTotal {
  country: string;
  donated: number;
  received: number;
}

export const COUNTRY_TOTAL: CountryTotal[] = [
  { country: "Afghanistan", donated: 0, received: 57 },
  { country: "Aland Islands", donated: 0, received: 0 },
  { country: "Albania", donated: 0, received: 117 },
  { country: "Algeria", donated: 0, received: 34 },
  { country: "Angola", donated: 0, received: 323 },
  { country: "Argentina", donated: 0, received: 8 },
  { country: "Armenia", donated: 0, received: 56 },
  { country: "Australia", donated: 48, received: 19 },
  { country: "Austria", donated: 958, received: 70 },
  { country: "Bangladesh", donated: 0, received: 4 },
  { country: "Belarus", donated: 0, received: 122 },
  { country: "Belgium", donated: 41, received: 35 },
  { country: "Belize", donated: 0, received: 74 },
  { country: "Benin", donated: 0, received: 116 },
  { country: "Bolivia", donated: 0, received: 215 },
  { country: "Bosnia and Herzegovina", donated: 0, received: 1178 },
  { country: "Brazil", donated: 0, received: 178 },
  { country: "Bulgaria", donated: 0, received: 55 },
  { country: "Burkina Faso", donated: 0, received: 152 },
  { country: "Burundi", donated: 0, received: 205 },
  { country: "Cambodia", donated: 0, received: 176 },
  { country: "Cameroon", donated: 0, received: 2405 },
  { country: "Cape Verde", donated: 0, received: 31 },
  { country: "Central African Republic", donated: 0, received: 21 },
  { country: "Chad", donated: 0, received: 3 },
  { country: "Chile", donated: 0, received: 5 },
  { country: "China", donated: 2, received: 36 },
  { country: "Colombia", donated: 82, received: 229 },
  { country: "Congo (Brazzaville)", donated: 0, received: 116 },
  { country: "Congo (Kinshasa)", donated: 0, received: 1938 },
  { country: "Costa Rica", donated: 0, received: 36 },
  { country: "Croatia", donated: 0, received: 8 },
  { country: "Cuba", donated: 0, received: 14 },
  { country: "Czech Republic", donated: 0, received: 4 },
  { country: "Denmark", donated: 0, received: 0 },
  { country: "Dominican Republic", donated: 0, received: 229 },
  { country: "Ecuador", donated: 0, received: 118 },
  { country: "Egypt", donated: 0, received: 28 },
  { country: "El Salvador", donated: 0, received: 12 },
  { country: "Ethiopia", donated: 0, received: 280 },
  { country: "Finland", donated: 0, received: 0 },
  { country: "France", donated: 32, received: 32 },
  { country: "Gabon", donated: 0, received: 10 },
  { country: "Gambia", donated: 0, received: 305 },
  { country: "Georgia", donated: 0, received: 36 },
  { country: "Germany", donated: 45502, received: 7180 },
  { country: "Ghana", donated: 0, received: 6496 },
  { country: "Greece", donated: 0, received: 450 },
  { country: "Guatemala", donated: 1, received: 81 },
  { country: "Guinea", donated: 0, received: 217 },
  { country: "Guinea-Bissau", donated: 0, received: 25 },
  { country: "Haiti", donated: 0, received: 178 },
  { country: "Honduras", donated: 0, received: 27 },
  { country: "Hong Kong S.A.R., China", donated: 24, received: 4 },
  { country: "Hungary", donated: 0, received: 29 },
  { country: "India", donated: 4, received: 442 },
  { country: "Indonesia", donated: 1, received: 40 },
  { country: "Iran", donated: 0, received: 3 },
  { country: "Iraq", donated: 0, received: 96 },
  { country: "Ireland", donated: 3, received: 14 },
  { country: "Israel", donated: 0, received: 2 },
  { country: "Italy", donated: 170, received: 59 },
  { country: "Ivory Coast", donated: 0, received: 12 },
  { country: "Japan", donated: 0, received: 0 },
  { country: "Jordan", donated: 0, received: 12 },
  { country: "Kazakhstan", donated: 0, received: 8 },
  { country: "Kenya", donated: 102, received: 1336 },
  { country: "Kyrgyzstan", donated: 0, received: 40 },
  { country: "Laos", donated: 0, received: 110 },
  { country: "Latvia", donated: 0, received: 0 },
  { country: "Lebanon", donated: 0, received: 225 },
  { country: "Liberia", donated: 0, received: 164 },
  { country: "Luxembourg", donated: 5, received: 0 },
  { country: "Macedonia", donated: 0, received: 23 },
  { country: "Madagascar", donated: 1, received: 60 },
  { country: "Malawi", donated: 0, received: 411 },
  { country: "Malaysia", donated: 0, received: 0 },
  { country: "Mali", donated: 0, received: 203 },
  { country: "Marshall Islands", donated: 0, received: 0 },
  { country: "Mauritania", donated: 0, received: 78 },
  { country: "Mexico", donated: 40, received: 205 },
  { country: "Mongolia", donated: 31, received: 335 },
  { country: "Montenegro", donated: 0, received: 0 },
  { country: "Morocco", donated: 74, received: 448 },
  { country: "Mozambique", donated: 0, received: 77 },
  { country: "Myanmar", donated: 0, received: 95 },
  { country: "Namibia", donated: 0, received: 313 },
  { country: "Nepal", donated: 0, received: 560 },
  { country: "Netherlands", donated: 9, received: 0 },
  { country: "New Zealand", donated: 184, received: 31 },
  { country: "Nicaragua", donated: 0, received: 57 },
  { country: "Nigeria", donated: 0, received: 1283 },
  { country: "Norway", donated: 15, received: 0 },
  { country: "Pakistan", donated: 0, received: 127 },
  { country: "Palestinian Territory", donated: 0, received: 34 },
  { country: "Panama", donated: 0, received: 3 },
  { country: "Paraguay", donated: 0, received: 63 },
  { country: "Peru", donated: 0, received: 66 },
  { country: "Philippines", donated: 0, received: 92 },
  { country: "Poland", donated: 9, received: 56 },
  { country: "Portugal", donated: 4, received: 10 },
  { country: "Romania", donated: 11, received: 574 },
  { country: "Russia", donated: 0, received: 9 },
  { country: "Rwanda", donated: 0, received: 34 },
  { country: "Senegal", donated: 0, received: 1137 },
  { country: "Serbia", donated: 0, received: 276 },
  { country: "Sierra Leone", donated: 0, received: 334 },
  { country: "Singapore", donated: 1, received: 0 },
  { country: "Slovenia", donated: 0, received: 0 },
  { country: "Solomon Islands", donated: 0, received: 2 },
  { country: "Somalia", donated: 0, received: 52 },
  { country: "South Africa", donated: 0, received: 592 },
  { country: "South Korea", donated: 0, received: 6 },
  { country: "South Sudan", donated: 0, received: 50 },
  { country: "Spain", donated: 6699, received: 2517 },
  { country: "Sri Lanka", donated: 0, received: 203 },
  { country: "Sudan", donated: 0, received: 22 },
  { country: "Swaziland", donated: 0, received: 119 },
  { country: "Sweden", donated: 10, received: 0 },
  { country: "Switzerland", donated: 7384, received: 571 },
  { country: "Syria", donated: 0, received: 75 },
  { country: "Taiwan", donated: 311, received: 15 },
  { country: "Tajikistan", donated: 0, received: 40 },
  { country: "Tanzania", donated: 4, received: 1553 },
  { country: "Thailand", donated: 6, received: 170 },
  { country: "Togo", donated: 0, received: 1085 },
  { country: "Tonga", donated: 0, received: 146 },
  { country: "Tunisia", donated: 0, received: 45 },
  { country: "Turkey", donated: 0, received: 227 },
  { country: "U.S. Virgin Islands", donated: 0, received: 2 },
  { country: "Uganda", donated: 0, received: 1939 },
  { country: "Ukraine", donated: 0, received: 1099 },
  { country: "United Arab Emirates", donated: 0, received: 0 },
  { country: "United Kingdom", donated: 46, received: 26 },
  { country: "United States", donated: 1193, received: 89 },
  { country: "Uruguay", donated: 0, received: 2 },
  { country: "Uzbekistan", donated: 0, received: 6 },
  { country: "Vanuatu", donated: 0, received: 40 },
  { country: "Venezuela", donated: 0, received: 12 },
  { country: "Vietnam", donated: 0, received: 109 },
  { country: "Western Sahara", donated: 0, received: 14 },
  { country: "Zambia", donated: 0, received: 918 },
  { country: "Zimbabwe", donated: 0, received: 100 },
  { country: "xx", donated: 1757, received: 100 },
];
